<?php

/**
 * @file
 * Contains oscar_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oscar_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oscar_core module.
    case 'help.page.oscar_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('bien cabron') . '</p>';
      return $output;

    default:
  }
}
